### ISSUE TITLE
佬，Mac系统怎么使用

### ISSUE THREAD

**Issue by YUHAN-GUO** [GangJust/AdbHelper#1]
/Users/xxx/Library/Android/sdk/platform-tools
是我传入的adb目录不对么？

**Comment by GangJust** [comment]
没在mac下跑过，可能命令行兼容有问题

**Comment by YUHAN-GUO** [comment]
/Users/xxx/Library/Android/sdk/platform-tools/adb version      这样ok  mac adb没有后缀
