### ISSUE TITLE
  屏幕截图 和 文件上传 在mac 里运行完程序无法使用

### ISSUE THREAD

**Issue by tianshaokai** [GangJust/AdbHelper#2]

**Comment by GangJust** [comment]
没在mac下跑过，可能命令行兼容有问题

**Comment by tianshaokai** [comment]
<img width="1836" alt="image" src="https://github.com/GangJust/AdbHelper/assets/6706496/9f9976f4-20fb-45e2-b156-aed462a42f95">

作者见过这个错误吗，看了好久不知道咋修复

**Comment by GangJust** [comment]
视图快照出问题了，看报错貌似是state在被重新赋值之前就已经调用了，这里在尝试读取一个在快照被创建之后的状态。

看样子要重新修改 state 的调用和赋值时机了，我大概看了一下之前的写法，发现有很多地方不太合理😵。

**Comment by tianshaokai** [comment]
作者是否还优化了，最好适配一下mac 截图和文件上传， 最好打成dmg 安装可用

**Comment by GangJust** [comment]
最近有点忙，偷闲的时候改改吧🌚🌚

**Comment by wenqian-cai-tuya** [comment]
mac m1，安装不了

**Comment by GangJust** [comment]
> mac m1，安装不了
> 

不应该啊，mac的产物就是在m1芯片下编译的，i系列的u用不了才正常哇😢
